#!/bin/bash

if [ ! -f "$1/publican.cfg" ]; then
    echo >&2 "Usage: $0 <path_to_guide_repo>"
    exit 1
fi

rm -rf  softwarecollections/static/guide
mkdir   softwarecollections/static/guide
cp -a   "$1/tmp/en-US/html-single"/{images,Common_Content} \
        softwarecollections/static/guide/

sed -r \
    -e 's@"(Common_Content|images)/@"/static/guide/\1/@g' \
    "$1/tmp/en-US/html-single/index.html" \
| ./guide-templatize > softwarecollections/templates/pages/en/docs/guide.html

