#!/usr/bin/env python3

import io
import sys

# read utf-8 content
content = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8').read()

# cut header
_, content = content.split('<div class="toc">', 1)

# cut end
content, _ = content.split('</body>')

# format output
out = '''
{% extends "section_docs_guide.html" %}}

{% block title %}Packaging Guide{% endblock %}

{% block content %}

<h1>Packaging Guide</h1>

<div class="para">
    The Packaging Guide provides an explanation of Software Collections and
    details how to build and package them. Developers and system administrators
    who have a basic understanding of software packaging with RPM packages, but
    who are new to the concept of Software Collections, can use this Guide to
    get started with Software Collections.
</div>

<div class="toc">''' + content + '''

{% endblock %}'''

# print output
io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8').write(out)

